name: "Zed Update"
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: "0 0 * * *" # runs daily at 00:00

jobs:
  update-zed:
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      - uses: cachix/install-nix-action@v30

      - name: Replace zed version by last preview release tag
        run: |
          url=https://api.github.com/repos/zed-industries/zed/releases
          last_preview=$(curl -s $url | jq -r 'map(select(.prerelease == true))[0].tag_name')
          echo "Last preview release tag: $last_preview"
          sed -Ei "s|(\"github:zed-industries/zed/).*\"|\1$last_preview\"|" flake.nix
          nix flake update zed-preview --accept-flake-config
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -am "Update zed version to $last_preview"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        id: update
        with:
          token: ${{ steps.app-token.outputs.token }}
          title: "Update zed version"
          body: |
            Automated update of zed to the latest preview release.
          branch: update_zed_action
          delete-branch: true
          labels: dependencies, zed, automated

      - name: Merge
        run: gh pr merge --auto "${{ steps.update.outputs.pull-request-number }}" --rebase
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        if: ${{ steps.update.outputs.pull-request-number != '' }}
